spring:
  application:
    name: cuenta-bancaria
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cuentasbanco
  cloud:
    config:
      import: configserver:http://localhost:8888
      enabled: true
      import-check:
        enabled: false

server:
  port: 8081
  servlet:
    context-path: /cuenta-bancaria
eureka:
  instance:
    instance-id: '${spring.application.name}:${random.value}'
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/