spring:
  application:
    name: cuenta-bancaria
  profiles:
    default: default
  config:
    import: "optional:configserver:http://localhost:7777"
server:
  port: 8081
  servlet:
    context-path: /cuenta-bancaria
eureka:
  instance:
    instance-id: '${spring.application.name}:${random.value}'
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/